# Generated by Django 5.2.13 on 2026-05-09 18:19

from django.db import migrations


def fill_price_at_order(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    items = OrderItem.objects.filter(price__isnull=True)
    for item in items:
        item.price = item.product.price
    OrderItem.objects.bulk_update(items, ['price'])    



class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_rename_first_name_order_firstname_and_more'),
    ]

    operations = [migrations.RunPython(fill_price_at_order)
    ]
