# Generated by Django 5.2.13 on 2026-05-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('CALL', 'Позвонили'), ('COOKING', 'Готовится'), ('DELIVERING', 'Доставка'), ('COMPLETED', 'Завершен')], db_index=True, default='NEW', max_length=20, verbose_name='Статус'),
        ),
    ]
