# Generated by Django 5.2.13 on 2026-05-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_alter_order_called_at_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('CASH', 'Наличные'), ('CASHLESS', 'Безнал')], db_index=True, max_length=10, null=True, verbose_name='Способ оплаты'),
        ),
    ]
