# Generated by Django 5.2.13 on 2026-05-17 18:33

from django.db import migrations

def convert_null_comments(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    Order.objects.filter(comment__isnull=True).update(comment='')
class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_alter_order_restaurant'),
    ]

    operations = [
        migrations.RunPython(convert_null_comments)
    ]
